Client/Maestro.Client/Areas/Admin/Controllers/EmployeesController.cs
using Maestro.Client.Services.External;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Maestro.Client.Areas.Admin.Controllers
{
    public class EmployeesController : BaseAdminController
    {
        private readonly IEmployeeGatewayService _employeeService;

        public EmployeesController(IEmployeeGatewayService employeeService)
        {
            _employeeService = employeeService;
        }

        public async Task<IActionResult> Index()
        {
            var employees = await _employeeService.GetEmployees();

            return View(employees);
        }
    }
}

Client/Maestro.Client/Areas/Admin/Controllers/UsersController.cs
using Client.Services.External;
using Maestro.Client.Models.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using static Core.Constants.Roles;
namespace Maestro.Client.Areas.Admin.Controllers
{
    /// <summary>
    ///  This controller will visualize all users
    ///  Will have functionality to promote from User to Employee and delete users
    /// /summary>
    public class UsersController : BaseAdminController
    {
        private readonly IIdentityService _identityService;

        public UsersController(IIdentityService identityService)
        {
            _identityService = identityService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _identityService.All();

            return View(model);
        }

        public async Task<IActionResult> PromoteToEmployee(string userId)
        {
            var model = new UserRoleInputModel { UserId = userId, Role = EmployeeRole };
            await _identityService.PromoteToEmployee(model);

            return RedirectToAction(nameof(Index));
        }      
    }
}

Client/Maestro.Client/Areas/Employee/Controllers/WorkController.cs
using Client.Services.External;
using Maestro.Client.Areas.Employee.ViewModels;
using Maestro.Client.Models.Employee;
using Maestro.Client.Models.Request;
using Maestro.Client.Services.External;
using Maestro.Core.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Core.Constants.Roles;
using static Maestro.Client.Constants.Area;

namespace Maestro.Client.Areas.Employee.Controllers
{
    [Authorize(Roles = EmployeeRole)]
    [Area(EmployeeArea)]
    public class WorkController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IRequestService _requestService;

        public WorkController(IEmployeeService employeeService, IRequestService requestService)
        {
            _employeeService = employeeService;
            _requestService = requestService;
        }

        public async Task<IActionResult> Mine()
        {
            var myWork = await _employeeService.MyWork();

            var model = await GetWorkViewModel(myWork.Work);

            return View(model);
        }

        public async Task<IActionResult> Available()
        {
            var available = await _employeeService.AvailableWork();

            var model = await GetWorkViewModel(available.Work);

            return View(model);
        }

        public async Task<IActionResult> TakeWork(string workId)
        {
            await _employeeService.TakeWork(new TakeWorkInputModel { Id = workId });

            return RedirectToAction(nameof(Mine));
        }

        public async Task<IActionResult> CloseWork(string workId)
        {
            await _employeeService.CloseWork(new WorkInputModel { Id = workId });

            return RedirectToAction(nameof(Mine));
        }

        private async Task<IEnumerable<WorkViewModel>> GetWorkViewModel(IEnumerable<WorkOutputModel> work)
        {
            var map = work.ToDictionary(x => x.RequestId);

            var requests = await _requestService
               .GetAllIn(new RequestsByIdsInputModel
               {
                   Ids = work.Select(w => w.RequestId)
               });

            return requests.Select(request =>
                  new WorkViewModel
                  {
                      Id = map[request.Id].Id,
                      CategoryName = request.CategoryName,
                      Description = request.Description,
                      StatusText = map[request.Id].Status.GetDescription(),
                      Status = map[request.Id].Status
                  });
        }
    }
}

Client/Maestro.Client/Controllers/RequestsController.cs
using Client.Services.External;
using Maestro.Client.Models.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize]
    public class RequestsController : BaseController
    {
        private readonly IRequestService _requestService;

        public RequestsController(IRequestService requestService)
        {
            _requestService = requestService;
        }

        [HttpGet]
        public async Task<IActionResult> New()
        {
            var model = await CreateRequestInputModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> New(RequestInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            return await Handle(async() => await _requestService.Create(model),
                RedirectToAction(nameof(Mine)), 
                View(model));
        }

        public async Task<IActionResult> Mine()
        {
            var requests = await _requestService.GetCurrentUserRequests();

            return View(requests);
        }
        private async Task<RequestInputModel> CreateRequestInputModel()
            => new RequestInputModel()
            {
                Categories = await _requestService.GetCategories()
            };
    }
}

Client/Maestro.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Maestro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/888fc36dbd.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Maestro</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(Roles.AdministratorRole))
                        {
                            <div class="dropdown">
                                <button class="btn btn-info dropdown-toggle"
                                        type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin panel
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-action="Index" asp-area="Admin" asp-controller="Users">Users</a>
                                    <a class="dropdown-item" asp-action="Index" asp-area="Admin" asp-controller="Employees">Employees</a>
                                </div>
                            </div>
                        }
                        @if (User.IsInRole(Roles.EmployeeRole))
                        {
                            <div class="dropdown">
                                <button class="btn btn-info dropdown-toggle"
                                        type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                   Employee panel
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-action="Available" asp-area="Employee" asp-controller="Work">Available work</a>
                                    <a class="dropdown-item" asp-action="Mine" asp-area="Employee" asp-controller="Work">My Work</a>
                                </div>
                            </div>
                        }
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="New">New request</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="Mine">Mine requests</a>
                            </li>
                            <li class="nav-item justify-content-end">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>